name: Reusable GitHub Sync PR
description: |
  This action runs the pulumi preview when opening a PR.

inputs:
  work_dir:
    required: false
    description: 'Where the Pulumi config are located.'
  stack_name:
    required: true
    description: 'Pulumi stack name.'
  pulumi_access_token:
    required: true
    description: 'Secret for accessing Pulumi.'

runs:
  using: "composite"

  steps:
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v3
      with:
        go-version: 1.18
        check-latest: true

    - name: Copy config to run pulumi
      run: |
        cp -r ${{ inputs.work_dir }} $GITHUB_ACTION_PATH
        ls -la $GITHUB_ACTION_PATH
      shell: bash

    - uses: pulumi/actions@d1936f654af277244c132c9c0cbb42c7ad81050a # v3
      with:
        command: preview
        stack-name: '${{ inputs.stack_name }}'
        refresh: false
        work-dir: '${{ env.GITHUB_ACTION_PATH }}'
      env:
        PULUMI_ACCESS_TOKEN: ${{ inputs.pulumi_access_token }}
